const event_images = [
    {url: '/photos/events/NuitDesDefis.png',name: 'Nuit des défis',date: 'Mardi 17 mai', desc:'La Nuit des Défis est l\'évènement phare de la pré-campagne. Notre liste s\'est donnée corps et âme entre 19h et 1h. Cette abnégation sans faille nous a apporté la victoire, qui nous a permise de choisir l\'emploi du temps de campagne.'},
    {url: '/photos/events/Tournoi.jpg',name: 'Tournoi multi-sports', date: 'Jeudi 19 mai', desc:'Notre tournoi, premier évènement de la campagne, présentait l\'originalité de proposer des matchs en deux mi-temps : une de spike, l\'autre d\'Ultimate. Il y en avait pour tous les goûts, et les participants ont eu la chance de se voir offrir une GoPro Hero 8, 4 WonderBox Sport Tendance et Extrême et presque 200€ de réduction au restaurant Living Room !'},
    {url: '/photos/events/TournoiESport.png',name: 'Tournoi E-Sport', date: 'Jeudi 19 mai', desc:'Pendant l\'Open Bouffe des Sportiates, les Homo Sporticus ont organisé un tournoi de Smash Bros et de Mario Kart. Il y a eu un tirage au sort parmi les particpants pour remporter une Nintendo Switch. Les gagnants des tournois ont chacun remporté un casque sans fil JBL. De quoi finir leur année en beauté !'},
    {url: '/photos/events/Cocktail.jpg',name: 'Cocktails', date: 'Jeudi 19 mai', desc:'Accompagné d\'un maître cocktailier tout droit venu de Saint Etienne, nous avons proposé des cocktails super goûtus et organisé une soirée cool à base de poker, billard, et sur fond de tournoi ESport. Les cocktails étaient tellement bons que, malheureusement, certains membres du bureau ne s\'en rappellent plus.'},
    {url: '/photos/events/SemaineDiversite.jpg',name: 'Semaine de la diversité', date: 'Vendredi 19 mai', desc:'Organisation de multiples activités de différentes origines afin de promouvoir des cultures sportives variées, et qui ciblent différents objectifs : \n Plumfoot (Chine) pour l\'adresse (pieds et mains) ; pétanque (France) pour la précision ; diabolo pour la dextérité et la dissociation main droite/main gauche ; course à l\'aveugle pour développer la collaboration et la communication ainsi que la proprioception (perception de l\'environnement indépendamment de la vue) ; nous avions préalablement contacté l\'administration afin d\'obtenir leur accord, en leur précisant les activités que nous allions mettre en place. Nous avons également tenu à récompenser les participants qui se sont le plus illustrés lors des activités, en leur offrant divers lots : une machine à café, des écouteurs bluetooth Sony, 3 repas gratuits chez le Pasta Bar Oh Mama, un jeu de pétanque (6 boules), et un jeu de Mölkky.'},
    {url: '/photos/events/PetitDejeuner.jpg',name: 'Petits déjeuners', date: 'Lundi 23 mai', desc:'Les Homo Sporticus se sont réveillés de bonne heure Lundi 23 Mai pour vous servir un petit déjeuner qui restera dans vos mémoires. Les Télécommiens ont pu se délecter d\'une multitude de bistoufailles qui ont rassasié leur ventre gargouillant.'},

];

module.exports = event_images;